# Generated by Django 5.2.4 on 2025-07-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielanguages',
            name='subtitle',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
    ]
