# Generated by Django 5.2.4 on 2025-07-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movielanguages_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielanguages',
            name='quality',
            field=models.CharField(choices=[('144p', '144p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='480', max_length=10),
        ),
    ]
